FROM aiogram/telegram-bot-api:latest

# Expose the HTTP port
EXPOSE 8081

# Set the command with the provided API credentials
CMD ["telegram-bot-api", \
     "--local", \
     "--api-id=25267962", \
     "--api-hash=976c013f306cc71b8454ca718ae74cd7", \
     "--http-port=8081"]
